- name: ping server
  hosts: all
  gather_facts: false

  tasks:
    - name: Verifying that a limit is set
      fail:
        msg: 'This playbook cannot be run with no limit'
      run_once: true
      when: ansible_limit is not defined

    - name: geather facts
      ansible.builtin.setup:
