---
- name: USER on AIX
  hosts: "{{host_name}}"
  gather_facts: false
  vars:
    host_name: usertest
    user_name: aixuser404
    password_val: abc123456
    attribute_home: /home/test/aixguest

  tasks:
    - name: Create user in LDAP
      ibm.power_aix.user:
        state: present
        name: "{{ user_name }}"
        change_passwd_on_login: false
        password: "{{ password_val }}"
        load_module: LDAP
        attributes:
          home: "{{ attribute_home }}"
          data: 1290
    - name: Create local user
      ibm.power_aix.user:
        state: present
        name: aixnewuser45
        change_passwd_on_login: false
        password: "{{ password_val }}"
        load_module: files
        attributes:
          home: "{{ attribute_home }}"
          data: 1291
    - name: Create a local user even if it is present in LDAP
      ibm.power_aix.user:
        state: present
        name: "{{ user_name }}"
        change_passwd_on_login: false
        password: "{{ password_val }}"
        load_module: files
        attributes:
          home: "{{ attribute_home }}"
          data: 1999
    - name: Modify locally present user
      ibm.power_aix.user:
        state: present
        name: "{{ user_name }}"
        load_module: files
        attributes:
          admin: true
    - name: Modify User present in LDAP
      ibm.power_aix.user:
        state: present
        name: "{{ user_name }}"
        load_module: LDAP
        attributes:
          admin: true
    - name: Delete Local user
      ibm.power_aix.user:
        state: absent
        name: "{{ user_name }}"
        load_module: files
        remove_homedir: false
    - name: Delete Local user
      ibm.power_aix.user:
        state: absent
        name: "{{ user_name }}"
        load_module: LDAP
        remove_homedir: false
