---
- name: Manage paging space in AIX
  hosts: "{{ hosts_val }}"
  gather_facts: false
  vars:
    hosts_val: all

  tasks:
    - name: Create a lv paging space
      ibm.power_aix.pagingspace:
        action: create
        activate_immediately: true
        ps_type: lv
        volume_group: rootvg
        logical_partitions: 2

    - name: Create a nfs paging space
      ibm.power_aix.pagingspace:
        action: create
        ps_type: nfs
        nfs_server_hostname: 10.32.148.131
        nfs_server_pathname: /tmp/nfsps

    - name: List paging space summary
      ibm.power_aix.pagingspace:
        action: list
        include_summary: true

    - name: List all paging space information
      ibm.power_aix.pagingspace:
        action: list
        list_all: true

    - name: Modify a particular paging space, add lpars and change checksum size
      ibm.power_aix.pagingspace:
        action: modify
        logical_partitions_add: 2
        checksum_size: 8
        use_on_next_swapon: true
        ps_name: paging00

    - name: Activate all paging spaces
      ibm.power_aix.pagingspace:
        action: activate
        activate_all_ps: true

    - name: Activate a paging space
      ibm.power_aix.pagingspace:
        action: activate
        ps_name: /dev/paging00

    - name: Activate a paging space
      ibm.power_aix.pagingspace:
        action: activate
        ps_name: /dev/paging00

    - name: Deactivate a paging space
      ibm.power_aix.pagingspace:
        action: deactivate
        ps_name: /dev/paging00

    - name: Remove a paging space
      ibm.power_aix.pagingspace:
        action: remove
        ps_name: paging00
